local_release_dir: "/tmp/releases"

kube_network_plugin: flannel
kube_service_addresses: 10.244.0.0/18
kube_pods_subnet: 10.244.64.0/18
kube_proxy_mode: iptables
kube_encrypt_secret_data: true
deploy_netchecker: true
container_manager: containerd
kubernetes_audit: true

helm_enabled: true
etcd_events_cluster_enabled: true
local_volume_provisioner_enabled: true
etcd_deployment_type: host
dns_min_replicas: 1
ingress_nginx_enabled: true
cert_manager_enabled: true
metrics_server_enabled: false
metrics_server_kubelet_insecure_tls: true
kube_token_auth: true
enable_nodelocaldns: false

# These are the current multicloud-k8s k8s-cluster.yml 

system_namespace: kube-system

#docker_version: 'latest'

kube_log_dir: "/var/log/kubernetes"

kube_api_anonymous_auth: true

kube_api_pwd: "secret"
kube_users:
  kube:
    pass: "{{kube_api_pwd}}"
    role: admin
    groups:
      - system:masters
kube_basic_auth: true
kube_token_auth: true

######## kube_network_plugin: flannel
kubeconfig_localhost: true
kubectl_localhost: true
######## enable_nodelocaldns: false
#local_volumes_enabled: true
######## local_volume_provisioner_enabled: true
######## helm_enabled: true
####download_run_once: True
######## local_release_dir: "/tmp/releases"
####download_localhost: True
######## kube_service_addresses: 10.244.0.0/18
######## kube_pods_subnet: 10.244.64.0/18

